server: https://idmeinc.atlassian.net/rest/
username: username
password: ""
project_id: CORE
jira_board: "23"
filename: data.json
app_key: key
app_secret: secret
member_token: token
trello_base: https://api.trello.com/1/
board_id: 5543ba1d19882538a1b79d35
priorities: ["--^-^-^-^-^--1--^-^-^-^-^--", "--^-^-^-^-^--2--^-^-^-^-^--", "--^-^-^-^-^--3--^-^-^-^-^--", "--^-^-^-^-^--4--^-^-^-^-^--", "--^-^-^-^-^--5--^-^-^-^-^--", "--V-V-V-V-V--NEW--V-V-V-V-V--"]